### PR TITLE
Update to 8.12.0

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note, this is untested. I'm not sure 8.12.x is a new major version (for semver purposes). It may or may not work (and would also need a new tag? and entry in NEWS?), but I doubt just changing to 11.0 would work (see my other issue).

**Comment by davidanthoff** [comment]
Thanks! All you need to do is also update the test files to test for the new version, and then I can merge!

**Comment by PallHaraldsson** [comment]
This seems now outdated so just close, with the updating to 10. I see 12 is now out however..., I assume 10 good enough for most.

Is there a good reason to use Julia with Node.JS over just Julia alone (unless you have some JS server code you want to use)? Julia alone is faster than with NodeJS, and I think the scalability issue was solved; should now be as good as with Go(?).

**Comment by davidanthoff** [comment]
My main use-case for this package is in VegaLite.jl, where it enables me to use the vega-lite javascript library from julia.

**Pull request closed without merging**
