### PR TITLE
Update to 8.9.3 for security

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note, I'm NOT sure this is sufficient. I'm not even a user.

I just noticed three CVEs e.g. on TLS and HTTP2:

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.3

In general, should I make such untested PRs? It's meant as a heads up? For this project at least should such minor number update only be ok?

I assume more changes to support 9.x; any idea if hard to do, or would even just changing the version number do?

**Comment by davidanthoff** [comment]
Yes, this kind of PR is certainly welcome, thanks! No worries about untested things, that is what we have travis and appveyor for.

I think the only additional thing that we need is that you also update the tests in ``runtests.jl``, and then I can merge and tag.

**Comment by PallHaraldsson** [comment]
I guess this works now then (and 9.x not need/would need more changes).

**Comment by davidanthoff** [comment]
Thanks!

**Pull request merged**
